#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const ll MOD = 998244353;

void solve(ll K, vector<ll> C){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll K;
    scanf("%lld", &K);
    vector<ll> C(26);
    for(int i = 0 ; i < 26 ; i++){
        scanf("%lld", &C[i]);
    }
    solve(K, move(C));
    return 0;
}
