#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, ll A, vector<ll> T){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll A;
    scanf("%lld", &A);
    vector<ll> T(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &T[i]);
    }
    solve(N, A, move(T));
    return 0;
}
