#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const string YES = "Yes";
const string NO = "No";

void solve(ll N, ll M, ll K){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll M;
    scanf("%lld", &M);
    ll K;
    scanf("%lld", &K);
    solve(N, M, K);
    return 0;
}
