#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll H, ll W, ll K, ll S_i, ll S_j, vector<vector<ll>> A){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll H;
    scanf("%lld", &H);
    ll W;
    scanf("%lld", &W);
    ll K;
    scanf("%lld", &K);
    ll S_i;
    scanf("%lld", &S_i);
    ll S_j;
    scanf("%lld", &S_j);
    vector<vector<ll>> A(H, vector<ll>(W));
    for(int i = 0 ; i < H ; i++){
        for(int j = 0 ; j < W ; j++){
            scanf("%lld", &A[i][j]);
        }
    }
    solve(H, W, K, S_i, S_j, move(A));
    return 0;
}
