#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, ll M, vector<string> S){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll M;
    scanf("%lld", &M);
    vector<string> S(N);
    for(int i = 0 ; i < N ; i++){
        cin >> S[i];
    }
    solve(N, M, move(S));
    return 0;
}
