#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const string YES = "Yes";
const string NO = "No";

void solve(string S, string T){

}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    string S;
    cin >> S;
    string T;
    cin >> T;
    solve(S, T);
    return 0;
}
